version: '3.8'
services:
  redis-broker:
    image: 'redis'

  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - ./dags:/usr/src/airflow/dags
      - ./plugins:/usr/src/airflow/plugins
      - ./logs:/usr/src/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__DAGS_FOLDER: /usr/src/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /usr/src/airflow/plugins
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /usr/src/airflow/logs
      AIRFLOW__CELERY__BROKER_URL: redis://redis-broker:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      DJANGO_DEFAULT_IMAGE: ${DJANGO_DEFAULT_IMAGE}
    command: airflow webserver
    depends_on:
      - redis-broker

  scheduler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - ./dags:/usr/src/airflow/dags
      - ./plugins:/usr/src/airflow/plugins
      - ./logs:/usr/src/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__DAGS_FOLDER: /usr/src/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /usr/src/airflow/plugins
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /usr/src/airflow/logs
      AIRFLOW__CELERY__BROKER_URL: redis://redis-broker:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      DJANGO_DEFAULT_IMAGE: ${DJANGO_DEFAULT_IMAGE}
    command: airflow scheduler
    depends_on:
      - webserver

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - ./dags:/usr/src/airflow/dags
      - ./plugins:/usr/src/airflow/plugins
      - ./logs:/usr/src/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__DAGS_FOLDER: /usr/src/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /usr/src/airflow/plugins
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /usr/src/airflow/logs
      AIRFLOW__CELERY__BROKER_URL: redis://redis-broker:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      DJANGO_DEFAULT_IMAGE: ${DJANGO_DEFAULT_IMAGE}
    command: airflow celery worker
    depends_on:
      - scheduler

  flower:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - ./dags:/usr/src/airflow/dags
      - ./plugins:/usr/src/airflow/plugins
      - ./logs:/usr/src/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5555:5555
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__DAGS_FOLDER: /usr/src/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /usr/src/airflow/plugins
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /usr/src/airflow/logs
      AIRFLOW__CELERY__BROKER_URL: redis://redis-broker:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      DJANGO_DEFAULT_IMAGE: ${DJANGO_DEFAULT_IMAGE}
    command: airflow celery flower
    depends_on:
      - redis-broker
