version: '3.8'
services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - ./dags:/usr/src/airflow/dags
      - ./plugins:/usr/src/airflow/plugins
      - ./logs:/usr/src/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__DAGS_FOLDER: /usr/src/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /usr/src/airflow/plugins
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /usr/src/airflow/logs
      DJANGO_DEFAULT_IMAGE: ${DJANGO_DEFAULT_IMAGE}
    command: airflow webserver

  scheduler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - ./dags:/usr/src/airflow/dags
      - ./plugins:/usr/src/airflow/plugins
      - ./logs:/usr/src/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__DAGS_FOLDER: /usr/src/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /usr/src/airflow/plugins
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /usr/src/airflow/logs
      DJANGO_DEFAULT_IMAGE: ${DJANGO_DEFAULT_IMAGE}
    command: airflow scheduler
